#Вспомогательный Makefile. Вызывает основной Makefile из родительской директории
# с теми же ключами
all:
	 $(MAKE) -C ../ all
clean:
	 $(MAKE) -C ../ clean
run:
	 $(MAKE) -C ../ run


.PHONY: all clean run



